//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceCuentaBancaria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCuentaBancaria.IServiceCuentaBancaria")]
    public interface IServiceCuentaBancaria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/Depositar", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/DepositarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.CuentaBancaria))]
        ML.Result Depositar(ML.CuentaBancaria cuentaBancaria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/Depositar", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/DepositarResponse")]
        System.Threading.Tasks.Task<ML.Result> DepositarAsync(ML.CuentaBancaria cuentaBancaria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/Retirar", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/RetirarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.CuentaBancaria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ML.Result Retirar(string NumeroCuenta, decimal Saldo, decimal SaldoARetirar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/Retirar", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/RetirarResponse")]
        System.Threading.Tasks.Task<ML.Result> RetirarAsync(string NumeroCuenta, decimal Saldo, decimal SaldoARetirar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/ConsultarSaldo", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/ConsultarSaldoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.CuentaBancaria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ML.Result ConsultarSaldo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCuentaBancaria/ConsultarSaldo", ReplyAction="http://tempuri.org/IServiceCuentaBancaria/ConsultarSaldoResponse")]
        System.Threading.Tasks.Task<ML.Result> ConsultarSaldoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCuentaBancariaChannel : PL.ServiceReferenceCuentaBancaria.IServiceCuentaBancaria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCuentaBancariaClient : System.ServiceModel.ClientBase<PL.ServiceReferenceCuentaBancaria.IServiceCuentaBancaria>, PL.ServiceReferenceCuentaBancaria.IServiceCuentaBancaria {
        
        public ServiceCuentaBancariaClient() {
        }
        
        public ServiceCuentaBancariaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCuentaBancariaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCuentaBancariaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCuentaBancariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result Depositar(ML.CuentaBancaria cuentaBancaria) {
            return base.Channel.Depositar(cuentaBancaria);
        }
        
        public System.Threading.Tasks.Task<ML.Result> DepositarAsync(ML.CuentaBancaria cuentaBancaria) {
            return base.Channel.DepositarAsync(cuentaBancaria);
        }
        
        public ML.Result Retirar(string NumeroCuenta, decimal Saldo, decimal SaldoARetirar) {
            return base.Channel.Retirar(NumeroCuenta, Saldo, SaldoARetirar);
        }
        
        public System.Threading.Tasks.Task<ML.Result> RetirarAsync(string NumeroCuenta, decimal Saldo, decimal SaldoARetirar) {
            return base.Channel.RetirarAsync(NumeroCuenta, Saldo, SaldoARetirar);
        }
        
        public ML.Result ConsultarSaldo() {
            return base.Channel.ConsultarSaldo();
        }
        
        public System.Threading.Tasks.Task<ML.Result> ConsultarSaldoAsync() {
            return base.Channel.ConsultarSaldoAsync();
        }
    }
}
